from dotenv import dotenv_values

CONFIG = dotenv_values(".env")

LLM_API_BASE_URL = str(CONFIG["LLM_API_BASE_URL"])
LLM_API_KEY = str(CONFIG["LLM_API_KEY"])
LLM_NAME = str(CONFIG["LLM_NAME"])

VLM_API_BASE_URL = str(CONFIG["VLM_API_BASE_URL"])
VLM_API_KEY = str(CONFIG["VLM_API_KEY"])
VLM_NAME = str(CONFIG["VLM_NAME"])

HF_TOKEN = str(CONFIG["HF_TOKEN"])
HF_LLM_NAME = str(CONFIG["HF_LLM_NAME"])

DEBUG_MODE = (
    True if (CONFIG.get("DEBUG_MODE") or "false").strip().lower() == "true" else False
)

CTX_WINDOW = int(CONFIG.get("CTX_WINDOW") or "8192")

CHUNK_MAX_TOKENS = int(CONFIG.get("CHUNK_MAX_TOKENS") or "128")

WARNING_TOK_FRAC = float(CONFIG.get("WARNING_TOK_FRAC") or "0.8")
FLUSH_TOK_FRAC = float(CONFIG.get("FLUSH_TOK_FRAC") or "0.95")
FLUSH_TGT_TOK_FRAC = float(CONFIG.get("FLUSH_TGT_TOK_FRAC") or "0.75")
FLUSH_MIN_FIFO_QUEUE_LEN = int(CONFIG.get("FLUSH_MIN_FIFO_QUEUE_LEN") or "5")

OVERTHINK_WARNING_HEARTBEAT_COUNT = int(
    CONFIG.get("OVERTHINK_WARNING_HEARTBEAT_COUNT") or "10"
)

PAGE_SIZE = int(CONFIG.get("PAGE_SIZE") or "10")
PERSONA_MAX_WORDS = int(CONFIG.get("PERSONA_MAX_WORDS") or "100")
